[package]

# Elision in Rust.
name = "reli"

# This project uses semantic versioning.  See:
# http://semver.org/ for details.
version = "0.0.1"

# The authors.
authors = ["Stacy J. Prowell <sprowell@gmail.com>"]
